os: linux
language: go
go:
- 1.16.2
- tip
env:
- APT_ENV=travis
services:
- postgresql
before_script:
- psql -c 'create database apt_registry_travis;' -U postgres
- psql -U postgres -d apt_registry_travis -a -f ./db/schema.sql
- "./bin/linux/cc-test-reporter before-build"
script:
- "./registry cover"
after_script:
- "./bin/linux/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  slack:
    secure: Yb/U9fWWe4mZKQvvkh9ESDYW2Gq1XFF36J6g9DL0cEU5f8/5a+yVgFa3amIjL1diaxr05HmsyNBIyVrgGcOLH8BUb1O4le5PeImgiUpmyc5EZAP4zJCnlXeCKFpvLFJyh6ZpQSDKiyWiasaAg57pt5bNLJTuxdj38W2nGGH2ovwlWuqZJXhlBeC93Oy2r6gyZ/AzlMKv5QeUo3R4qJlwDmbyNNmtkOTsLizdfXTW3X/fUq/FTs5CpdJMAK44NB1smc78tMOD9fopV2HXyyk46qlpfW80IDwWLhE9DMz1UAY5hLW+wKv4DYQ9NDN/fV4pZcG+MzC/PSWJpjqKo71jJ4NxUxLUmIdOhWzQKGE9F/sMg1XJLg8pxhx23+XeDUP0pU7uxsGu4Vkt9ZUq+YLzAUr5OYnOHkfj5WhHrYO2/4H8vHDX3/HfPfG42C+i6ctByKnetA6h3ejgShmaiCNbLWdg8WZtWewgrPGU/QH9Ik/mUgC3bc9G8k/Lx4uMm+7HlD6TFQSGxZRx4o2hwj/52fqe9HX40cy7Imo44ZVff+FQK8pf+C10I/zLHsamBfx9B1gPBu/X4nw33gIfkX3BaTzsqAAGSCGckAh06fy5Z4GPt4+lwEt+dGPc7xdNgJU1VWicpZL/7BzipUoB3ze9ivN0Uu/82ZetTglnNDWci00=
branches:
  only:
  - "/.*/"
